//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTask.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class university
    {
        public university()
        {
            this.students = new HashSet<student>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string town { get; set; }
        public int rating { get; set; }
    
        public virtual ICollection<student> students { get; set; }
    }
}
